POST http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{
  "username": "usertest",
  "name":" token",
  "password": "password"
}

####

POST http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{
  "username": "loginTest",
  "name":"Login",
  "password":"password123"
}

